export const getData = () => [
    { type: "header", content: "1. Introduction" },
    { type: "text", content: `Neroli Properties ("we", "us", "our") respects your privacy and is committed to protecting your personal information. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website [Your Website URL].` },
    { type: "header", content: "2. Information Collection" },
    {type: "text", content: "We, at Neroli Properties, collect information from you when you visit our website, register on our site, subscribe to a newsletter, fill out a form, or enter information on our site. The information collected may include your name, email address, phone number, and other details necessary to provide our services."},
    {type: "header", content: "3. Use of Information" },
    {type: "text", content: "The information we collect from you at Neroli Properties may be used in one of the following ways:"},
    {type: "list", content: ["To personalize your experience and to allow us to deliver the type of content and product offerings in which you are most interested.", "To improve our website, Neroli Properties, in order to better serve you.", "To allow us to better respond to your customer service requests.", "To send periodic emails regarding your order or other products and services from Neroli Properties."]},
    {type: "header", content: "4. Protection of Information" },
    {type: "text", content: "At Neroli Properties, we implement a variety of security measures to maintain the safety of your personal information. However, no method of transmission over the Internet or method of electronic storage is 100% secure."},
    {type: "header", content: "5. Disclosure of Information to Third Parties" },
    {type: "text", content: "Neroli Properties does not sell, trade, or otherwise transfer to outside parties your personally identifiable information unless we provide you with advance notice. This does not include website hosting partners and other parties who assist us in operating our website, conducting our business, or serving our users at Neroli Properties, so long as those parties agree to keep this information confidential."},
    {type: "header", content: "6. Third-Party Links" },
    {type: "text", content: "Occasionally, at our discretion, Neroli Properties may include or offer third-party products or services on our website. These third-party sites have separate and independent privacy policies."},
    {type: "header", content: "7. Your Consent" },
    {type: "text", content: "By using our site at Neroli Properties, you consent to our website's privacy policy."},
    {type: "header", content: "8. Changes to Our Privacy Policy" },
    {type: "text", content: "Neroli Properties reserves the right to update or change our Privacy Policy at any time, and you should check this Privacy Policy periodically. Your continued use of the service after we post any modifications to the Privacy Policy on this page will constitute your acknowledgment of the modifications and your consent to abide and be bound by the modified Privacy Policy."},
    {type: "header", content: "9. Contacting Us" },
    {type: "text", content: "In compliance with the General Data Protection Regulation (GDPR), Neroli Properties is dedicated to safeguarding the personal data of our European Union (EU) visitors and customers. We process all personal data in accordance with GDPR requirements directly or through our vendors. If there are any questions regarding this privacy policy, or if you would like to exercise any of your rights under the GDPR, you may contact Neroli Properties using the information on our website."},
]