export const getData = () => [
    { type: "text", content: "Welcome to neroli.com!" },
    { type: "text", content: "These terms and conditions outline the rules and regulations for the use of Neroli's Website, located at neroli.com." },
    { type: "text", content: "By accessing this website we assume you accept these terms and conditions. Do not continue to use neroli.com if you do not agree to take all of the terms and conditions stated on this page." },
    { type: "text", content:  `The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice and all Agreements: "Client", "You" and "Your" refers to you, the person log on this website and compliant to the Company's terms and conditions. "The Company", "Ourselves", "We", "Our" and "Us", refers to our Company. "Party", "Parties", or "Us", refers to both the Client and ourselves. All terms refer to the offer, acceptance and consideration of payment necessary to undertake the process of our assistance to the Client in the most appropriate manner for the express purpose of meeting the Client's needs in respect of provision of the Company's stated services, in accordance with and subject to, prevailing law of af. Any use of the above terminology or other words in the singular, plural, capitalization and/or he/she or they, are taken as interchangeable and therefore as referring to same.`},
    { type: "header", content: "Cookies" },
    { type: "text", content: "We employ the use of cookies. By accessing neroli.com, you agreed to use cookies in agreement with the Neroli's Privacy Policy." },
    { type: "text", content: "Most interactive websites use cookies to let us retrieve the user's details for each visit. Cookies are used by our website to enable the functionality of certain areas to make it easier for people visiting our website. Some of our affiliate/advertising partners may also use cookies." },
    { type: "header", content: "License" },
    { type: "text", content: "Unless otherwise stated, Neroli and/or its licensors own the intellectual property rights for all material on neroli.com. All intellectual property rights are reserved. You may access this from neroli.com for your own personal use subjected to restrictions set in these terms and conditions." },
    { type: "text", content: "You must not:" },
    { type: "list", content: ["Republish material from neroli.com", "Sell, rent or sub - license material from neroli.com", "Reproduce, duplicate or copy material from neroli.com","Redistribute content from neroli.com"]},
    { type: "text", content: "Parts of this website offer an opportunity for users to post and exchange opinions and information in certain areas of the website. Neroli does not filter, edit, publish or review Comments prior to their presence on the website. Comments do not reflect the views and opinions of Neroli, its agents and/or affiliates. Comments reflect the views and opinions of the person who post their views and opinions. To the extent permitted by applicable laws, Neroli shall not be liable for the Comments or for any liability, damages or expenses caused and/or suffered as a result of any use of and/or posting of and/or appearance of the Comments on this website." },
]