export const getData = () => [
    { type: "header", content: "1. Introduction" },
    { type: "text", content: "Welcome to the Neroli Properties website. By accessing or using our website, you agree to be bound by the following terms and conditions (the \"Terms\"). Please read them carefully." },
    { type: "header", content: "2. Use of the Website" },
    { type: "text", content: "This website is offered to you, the user, conditioned on your acceptance without modification of the terms, conditions, and notices contained herein. Your use of the Neroli Properties website constitutes your agreement to all such terms, conditions, and notices." },
    { type: "header", content: "3. Privacy" },
    { type: "text", content: "Your use of this website is subject to the Neroli Properties Privacy Policy. Please review our Privacy Policy, which also governs the Site and informs users of our data collection practices." },
    { type: "header", content: "4. Modification of These Terms of Use" },
    { type: "text", content: "Neroli Properties reserves the right to change the terms, conditions, and notices under which the Neroli Properties website is offered, including but not limited to the charges associated with the use of the Neroli Properties website." },
    { type: "header", content: "5. Links to Third Party Sites" },
    { type: "text", content: "The Neroli Properties website may contain links to other websites (\"Linked Sites\"). The Linked Sites are not under the control of Neroli Properties, and Neroli Properties is not responsible for the contents of any Linked Site, including without limitation any link contained in a Linked Site, or any changes or updates to a Linked Site." },
    { type: "header", content: "6. No Unlawful or Prohibited Use" },
    { type: "text", content: "As a condition of your use of the Neroli Properties website, you warrant to Neroli Properties that you will not use the Neroli Properties website for any purpose that is unlawful or prohibited by these terms, conditions, and notices." },
    { type: "header", content: "7. Disclaimer" },
    { type: "text", content: "The information, software, products, and services included in or available through the Neroli Properties website may include inaccuracies or typographical errors. Changes are periodically added to the information herein. Neroli Properties and/or its suppliers may make improvements and/or changes in the Neroli Properties website at any time." },
    { type: "header", content: "8. Limitation of Liability" },
    { type: "text", content: "In no event shall Neroli Properties and/or its suppliers be liable for any direct, indirect, punitive, incidental, special, consequential damages or any damages whatsoever including, without limitation, damages for loss of use, data or profits, arising out of or in any way connected with the use or performance of the Neroli Properties website." },
    { type: "header", content: "9. Indemnification" },
    { type: "text", content: "You agree to indemnify, defend and hold harmless Neroli Properties, its officers, directors, employees, agents, and third parties, for any losses, costs, liabilities and expenses (including reasonable attorney's fees) relating to or arising out of your use of or inability to use the Site or services." },
    { type: "header", content: "10. Governing Law" },
    { type: "text", content: "To the maximum extent permitted by law, this agreement is governed by the laws of the Dubai, United Arab Emirates where Neroli Properties is located, and you hereby consent to the exclusive jurisdiction and venue of courts in that Dubai, United Arab Emirates in all disputes arising out of or relating to the use of the Neroli Properties website." },
]